[project]
name = "alx-be-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "django>=5.2.7",
    "mysql>=0.0.3",
    "mysql-connector-python>=9.4.0",
]
